---
# This playbook will Init Docker Swarm

#- debug: msg="System {{ inventory_hostname }} has uuid {{ ansible_product_uuid }}"

- name: Check if this docker host is in Swarm Node
  stat: path=/var/lib/docker/swarm/state.json
  register: swarm_stat 
  
- name: Init Docker Swarm 
  shell: docker swarm init --advertise-addr {{ ansible_host }} --listen-addr {{ ansible_eth0.ipv4.address }}
  when: swarm_stat.stat.exists == false
  
- name: Get Docker Swarm Manager Token
  shell: docker swarm join-token -q manager
  register: manager_token
  changed_when: False

- name: Save Docker Swarm Manager Token
  set_fact: swarm_manager_token="{{ manager_token.stdout }}"

- name: Get Docker Swarm Worker Token
  shell: docker swarm join-token -q worker
  register: worker_token
  changed_when: False

- name: Save Docker Swarm Worker Token
  set_fact: swarm_worker_token="{{ worker_token.stdout }}"

